development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://irhfyhvaffykrk:a28874841c4073f7169ff31fc38e29a0e94e77feb0add0eb10b8da37ca462ce1@ec2-54-197-254-189.compute-1.amazonaws.com:5432/d276u9fuej0n8c
  channel_prefix: ruthapp_production
